export interface profileModal{        
    email:string 
    userphone:string
    sex:string
    height:number
    weight:number
    age:number
    birth:string
    signupdate:string
    sleeptime:number
    uptime:number
    bpm:number
    step:number
    distanceKM:number
    cal:number
    calexe:number
    alarm_sms:number
    differtime:number
    phone:string
    arrCnt:number
}