name: Deploy to cloudtype
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gtrrpc2001/react_msl_admin_web
          stage: main
          yaml: >
            name: deploy-vite

            app: web

            options:
              nodeversion: "22"
              build: pnpm build;
              spa: true
              install: npm install -g pnpm; pnpm install;
              buildenv:
                - name: VITE_API_BASEURL
                  value: ${{ secrets.VITE_API_BASEURL }}
                - name: VITE_API_DEPLOY
                  value: ${{ secrets.VITE_API_DEPLOY }}
                - name: VITE_API_ADMIN
                  value: ${{ secrets.VITE_API_ADMIN }}
                - name: VITE_API_BUSINESS
                  value: ${{ secrets.VITE_API_BUSINESS }}
                - name: VITE_API_BUSINESS2
                  value: ${{ secrets.VITE_API_BUSINESS2 }}
                - name: VITE_API_BUSINESS2
                  value: ${{ secrets.VITE_API_DATA_SECRET_KEY }}                  
              rewrites: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react-vite
